image: maven:3.8.7-eclipse-temurin-17-alpine

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  IMAGE_NAME: ' amsidhmicroservice/gitlab-project-demo'
  IMAGE_TAG: '0.0.1-SNAPSHOT'

stages:
  - build
  - test
  - package
  - docker_build_push

cache:
  paths:
    - .m2/repository
    - target



build_job:
  stage: build
  tags:
    - docker
  script:
    - echo "Maven compile started"
    - "mvn compile"

test_job:
  stage: test
  tags:
    - docker
  script:
    - echo "Maven test started"
    - "mvn test"

package_job:
  stage: package
  tags:
    - docker
  script:
    - echo "Maven packaging started"
    - "mvn package"

docker_build_push_job:
  stage: docker_build_push
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build --pull -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker push "$IMAGE_NAME:$IMAGE_TAG"